### ISSUE TITLE
Enhance Feature Request issue template

### ISSUE THREAD

**Issue by FrugalGuy** [TriEmbed/quercus#38]
Create a template that visitors can use to request a feature.   
We encourage contributions, so we hope this will also be used to document a PR used to offer new features.

- ❓: What fields are needed? I'm providing a starter. Comments are very welcome.

**Comment by FrugalGuy** [comment]
From @petesoper :

> The issues/feature request page has several items that I don't understand such as "implementation PR". Does that imply the submitter is describing a feature and providing the code to implement it?

> OK, I think I get this page. It seems like a good start to me.

**Comment by FrugalGuy** [comment]
Thanks, @petesoper !

> ... "implementation PR". Does that imply the submitter is describing a feature and providing the code to implement it?

Yeah, I'll clarify that is optional, and that it can be used if there is a PR ready to submit.

**Comment by FrugalGuy** [comment]
I added a `feature request` label and had it automatically applied to issues created using the template.
Closing issue.

**Comment by petesoper** [comment]
Well, if we were the Sun Solaris architecture committee I'd suggest a series of questions to force the submitter to *really* think through what they were proposing and come back when they are all answered. But this is not an enterprise OS that has to have features that stand the test of time, repel Javelin missiles, etc. That would be nice, but the barrier to entry of a proposal should be relatively low. While earnestly hoping others will chime in (I left Sun 14 years ago and memories fade) I think two text boxes might work: "Describe the feature/enhancement request" and "describe any work that has been done to design, document, implement and test the feature/enhancement". Oh, an email address to send patches would be good. Hmm, this might work as a "user group address" too. How about ***@***.***? I could create a forwarder that goes to us or some subset of us. Holler if you incorporate this so I remember to create the forwarder.

Aug 27, 2022 11:40:40 AM Ron Craig ***@***.***>:

> Create a template that visitors can use to request a feature.
> We encourage contributions, so we hope this will also be used to document a PR used to offer new features.
> 
* > ❓ : What fields are needed? I'm providing a starter. Comments are very welcome.

**Comment by FrugalGuy** [comment]
> Oh, an email address to send patches would be good. Hmm, this might work as a "user group address" too. How about @.***? I could create a forwarder that goes to us or some subset of us. Holler if you incorporate this so I remember to create the forwarder.

Actually a PR is, in effect, a patch.  Using github, folks don't email those around, they create a PR, and the review team gets notified to review it.  The PR will mention this issue number, and we've given a field above for the reverse.

**Comment by FrugalGuy** [comment]
>  "Describe the feature/enhancement request" and "describe any work that has been done to design, document, implement and test the feature/enhancement". 

That's covered, now.  I updated the field text label, and if there's work done, you see it through the PR, or they can add that info in the existing fields
Note also that most fields are not required.  We can adjust that as needed, too.
