### ISSUE TITLE
Consider making esp-idf clone/prep separate from -targetdir dirs

### ISSUE THREAD

**Issue by petesoper** [TriEmbed/quercus#5]
It would probably be better to make the cloning/prep of the Espressif IDF treated as a "one time" operation with a separate default and targeted directory with the default being $HOME. It is a frequent source of confusion and problems to believe that a "collection" of esp-idf clones in different directories are actually available. The truth is that the clone where install.sh was executed most recently is "it" and export.sh does NOT implicitly repeat install.sh actions. 

The proposal is to have installit recognize option switch "-targetidfdir" (that begs the question of whether underscores should be used in the option names!). This would correspond to internal variable targetidfdir that would default to $HOME (aka ~) and that directory would could esp-idf. The expectation is that 99% of the time almost all users will clone esp-idf exactly once until/unless the stable version changes (a few of the developers being the exception). 

This change will allow for easy creation of multiple target directories for customized que_ant (and possibly que_aardvark) repos while avoiding the large disk space penalty of redundant IDF clones. Also, it should be pointed out that the expectation is that soon there will be a convention for having user-defined code to provide "applications" for que_ant instances as the ESP32 is engaged to do more than just program an FPGA. This use case will tend to drive the generation of case-specific collections of the two repos.

**Comment by RobMackie** [comment]
The basic idea of this works for me. I hate having my $HOME directory name space poluted with many many things. However, I like the idea of a default so I don't have to remember where i last pointed -targetidfdir.  What if we created a dot directory off $HOME. Something like   ~/.quercus and put anything like this including "config files" and other things that we may eventually want to persist to make the installit script easier and other things easier (like Carl wants to do with installit)

I'd be happy for that to be the default and then of course people could override it. 

Dot files in the home directory are kind of a linux convention.

execute this command
ls -a | grep "^\."
in your home directory and see how many apps have set something like that up if this is new to anyone. I know vim does it, bash does it, I think i remember that emacs does it, netscape and chrome do it. etc.  On one of my linux boxen, I ran that command and the output had 43 files and/or directories that started with a "."   Linux nicely hides those from you so the namespace isn't so cluttered.

**Comment by petesoper** [comment]
For some reason your comment caused me to have a flash about how existing ESP32 users might react to the behavior of the Quercus installer. My intuition is telling me we need to eventually be able to use "their" esp-idf if possible vs doing a clone. So in addition to avoiding $HOME (aka ~) and putting esp-idf in .quercus I think if the idf target dir option points to an existing esp-idf we should do what we do now in the short term but try hard to use the repo later. For instance, it may be that a range of versions can be made to work but as things stand right now v4.4 and v5.0 should be used if possible. A bit smarter probing of the idf repo can eventually be done. Of course the idf.py build of que_ant can just be tried and if it doesn't work the error messages could be parsed to decide whether a clone is required. 
So what about this behavior: with no option then if an existing repo is found in ~/.quercus/esp-idf then fine, else the clone and submodule fetching happens with that path. However, if the option switch is used then *sooner* the current checks will be done that the thing is usable else clone/submodules. But *later* the script code will be smarter to make a best effort to use the existing esp-idf, assuming it was installed by somebody prior to using Quercus.

**Comment by RobMackie** [comment]
That sounds great!

**Comment by petesoper** [comment]
This will be satisfied when issue # "7/18/22 installit change bundle" is completed.
